#!/usr/bin/env python3
"""Writes the OpenSCAD include of the open reference cup from its dimensions.

validation/reference_cup/dimensions.json is the single source of the cup's
geometry: the CAD reads it through geometry/dimensions.scad (this script's
output) and the netlist examples/reference_cup.json carries its "model"
entries as parameters. crates/acoustilab/tests/reference_cup.rs checks
both, so the three cannot drift apart.

    python3 tools/refcup/dims_to_scad.py            # write the include
    python3 tools/refcup/dims_to_scad.py --check    # exit 1 if it is stale

Standard library only.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DIMS = ROOT / "validation/reference_cup/dimensions.json"
OUT = ROOT / "validation/reference_cup/geometry/dimensions.scad"


def number(x):
    """Shortest text of a number, as Rust's and Python's repr write it."""
    if isinstance(x, bool) or not isinstance(x, (int, float)):
        raise SystemExit(f"not a number: {x!r}")
    if isinstance(x, int) or float(x).is_integer():
        return str(int(x))
    return repr(float(x))


def render(dims):
    lines = [
        "// Generated by tools/refcup/dims_to_scad.py from",
        "// validation/reference_cup/dimensions.json. Do not edit: edit the JSON",
        "// and run the script (cargo test checks that this file is current).",
        f"// Licence: {dims['licence']}",
        "",
    ]
    for name, d in dims["dimensions"].items():
        lines.append(f"{name} = {number(d['value'])};")
    return "\n".join(lines) + "\n"


def main():
    dims = json.loads(DIMS.read_text())
    text = render(dims)
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT} is stale: run tools/refcup/dims_to_scad.py", file=sys.stderr)
            sys.exit(1)
        print("dimensions.scad is current")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
