// Generated by tools/audio/pink_kellet.py; do not edit by hand.
//
// Paul Kellet's "refined" pink-noise filter (music-dsp mailing list,
// 17 October 1999, quoted at https://www.firstpr.com.au/dsp/pink-noise/,
// retrieved 2026-09-25): H(z) = Σ_i g_i/(1 − p_i·z⁻¹) + d + e·z⁻¹, driven
// by white noise. 44.1 kHz: the published coefficients; other rates:
// refitted to 10·log10(C/f) (poles and gains free, least squares on the
// dB error, reweighted towards minimax), see the script's docstring. All
// are scaled to |H| = 1 at 1 kHz. maxErrorDb is the largest deviation
// from −3.01 dB/octave over the fit band (9.2 Hz·fs/44.1 kHz to 0.9 of
// Nyquist), maxErrorAudioDb over 20 Hz–20 kHz.

export interface PinkCoefficients {
  poles: number[];
  gains: number[];
  direct: number;
  delayed: number;
  kind: string;
  fitBandHz: [number, number];
  maxErrorDb: number;
  maxErrorAudioDb: number;
}

export const PINK_KELLET: Record<number, PinkCoefficients> = {
  44100: {
    poles: [0.99886, 0.99332, 0.969, 0.8665, 0.55, -0.7616],
    gains: [0.011788331827284825, 0.015941158102738984, 0.032667994075630105, 0.06592661610748289, 0.11316381530427964, -0.0035880181205964015],
    direct: 0.1138534333213274,
    delayed: 0.024615018857158152,
    kind: "published (Kellet 1999), scaled to unit gain at 1 kHz",
    fitBandHz: [9.2, 19845.0],
    maxErrorDb: 0.03761012749630055,
    maxErrorAudioDb: 0.03264097879289096,
  },
  48000: {
    poles: [0.9988805963370088, 0.993473316972897, 0.9704058918658008, 0.8759971558447164, 0.5754316363880617, -0.8427414383312413],
    gains: [0.01120153634320062, 0.014989611002355666, 0.03000597719065772, 0.059562719515519495, 0.10914662704858596, -0.0049655654725744005],
    direct: 0.11451869533772119,
    delayed: 0.02516859080071654,
    kind: "refitted (tools/audio/pink_kellet.py)",
    fitBandHz: [10.01360544217687, 21600.0],
    maxErrorDb: 0.030511856243339963,
    maxErrorAudioDb: 0.02783932238910225,
  },
  88200: {
    poles: [0.9988805957558133, 0.9934733124302166, 0.9704058741373963, 0.8759970760641879, 0.5754312326124609, -0.8427141747410064],
    gains: [0.008303328724607144, 0.011111303600448123, 0.02224243610643308, 0.04415188118774807, 0.08090680307697155, -0.0036803615715003146],
    direct: 0.08488878458081335,
    delayed: 0.018656527357477217,
    kind: "refitted (tools/audio/pink_kellet.py)",
    fitBandHz: [18.4, 39690.0],
    maxErrorDb: 0.030511939252892972,
    maxErrorAudioDb: 0.029959823107642336,
  },
  96000: {
    poles: [0.9988805967226249, 0.993473321196046, 0.9704059184139701, 0.8759972449034337, 0.5754317468655993, -0.8427366189461484],
    gains: [0.007961278760520402, 0.010657815088427568, 0.021371402007064555, 0.04274156890376234, 0.08069219903797369, -0.04633312969943923],
    direct: 0.08814986622227408,
    delayed: 0.02071465936585145,
    kind: "refitted (tools/audio/pink_kellet.py)",
    fitBandHz: [20.02721088435374, 43200.0],
    maxErrorDb: 0.030511802036073732,
    maxErrorAudioDb: 0.03108266881751831,
  },
};
