// Generated by tools/audio/pink_kellet.py; do not edit by hand.
//
// Paul Kellet's "refined" pink-noise filter (music-dsp mailing list,
// 17 October 1999, quoted at https://www.firstpr.com.au/dsp/pink-noise/,
// retrieved 2026-09-25): H(z) = Σ_i g_i/(1 − p_i·z⁻¹) + d + e·z⁻¹, driven
// by white noise. 44.1 kHz: the published coefficients; other rates:
// refitted to 10·log10(C/f) (poles and gains free, least squares on the
// dB error, reweighted towards minimax), see the script's docstring. All
// are scaled to |H| = 1 at 1 kHz. maxErrorDb is the largest deviation
// from −3.01 dB/octave over the fit band (9.2 Hz·fs/44.1 kHz to 0.9 of
// Nyquist), maxErrorAudioDb over 20 Hz–20 kHz.

export interface PinkCoefficients {
  poles: number[];
  gains: number[];
  direct: number;
  delayed: number;
  kind: string;
  fitBandHz: [number, number];
  maxErrorDb: number;
  maxErrorAudioDb: number;
}

export const PINK_KELLET: Record<number, PinkCoefficients> = {
  44100: {
    poles: [0.99886, 0.99332, 0.969, 0.8665, 0.55, -0.7616],
    gains: [0.011788331827284825, 0.015941158102738984, 0.032667994075630105, 0.06592661610748289, 0.11316381530427964, -0.0035880181205964015],
    direct: 0.1138534333213274,
    delayed: 0.024615018857158152,
    kind: "published (Kellet 1999), scaled to unit gain at 1 kHz",
    fitBandHz: [9.2, 19845.0],
    maxErrorDb: 0.03761012749630055,
    maxErrorAudioDb: 0.03264097879289096,
  },
  48000: {
    poles: [0.9988805958022197, 0.993473313653525, 0.9704058846348491, 0.8759970906326161, 0.5754311648612174, -0.842713610638214],
    gains: [0.011202458866360026, 0.014996806813358157, 0.030072097381998064, 0.060142566011155, 0.11354435833507255, -0.06520720420284883],
    direct: 0.12403895835167943,
    delayed: 0.02914863847987266,
    kind: "refitted (tools/audio/pink_kellet.py)",
    fitBandHz: [10.01360544217687, 21600.0],
    maxErrorDb: 0.030511951253117786,
    maxErrorAudioDb: 0.027839297045744615,
  },
  88200: {
    poles: [0.998880595843125, 0.9934733134167838, 0.9704058808385311, 0.8759970925532882, 0.5754313129441048, -1.186626054718819],
    gains: [0.008309943772448142, 0.011163157682650417, 0.022722645102652646, 0.04850710288655436, 0.11929471488773467, -0.0032878316208637065],
    direct: -0.16589493413374587,
    delayed: 0.1133268115192838,
    kind: "refitted (tools/audio/pink_kellet.py)",
    fitBandHz: [18.4, 39690.0],
    maxErrorDb: 0.030511937976083203,
    maxErrorAudioDb: 0.02995980599410686,
  },
  96000: {
    poles: [0.9988805954492986, 0.9934733097042614, 0.9704058639360265, 0.8759970857948116, 0.5754315965068278, -1.1865899397146575],
    gains: [0.007966320404738677, 0.01069729863604759, 0.021736945148741044, 0.04605687623910678, 0.10994265328198188, -0.04138578644234333],
    direct: -0.10969784362228938,
    delayed: 0.09381804732731523,
    kind: "refitted (tools/audio/pink_kellet.py)",
    fitBandHz: [20.02721088435374, 43200.0],
    maxErrorDb: 0.030512007718169087,
    maxErrorAudioDb: 0.031082874938768157,
  },
};
