// Generated by tools/refcup/dims_to_scad.py from
// validation/reference_cup/dimensions.json. Do not edit: edit the JSON
// and run the script (cargo test checks that this file is current).
// Licence: CC-BY-4.0 (https://creativecommons.org/licenses/by/4.0/). Attribution: AcoustiLab open reference cup.

driver_outer_diameter_mm = 39.9;
driver_body_depth_mm = 6.5;
driver_overall_depth_mm = 7.5;
driver_rear_boss_diameter_mm = 22;
diaphragm_setback_mm = 0.5;
seat_clearance_mm = 0.15;
lip_inner_diameter_mm = 38;
lip_thickness_mm = 1.2;
driver_gasket_mm = 0.3;
retainer_inner_diameter_mm = 38;
retainer_outer_diameter_mm = 50;
retainer_thickness_mm = 2;
retainer_screw_circle_mm = 46;
retainer_screws = 3;
cup_inner_diameter_mm = 66;
pad_ring_width_mm = 12;
pad_ring_height_mm = 22;
gasket_thickness_mm = 3;
gasket_compressed_mm = 2.9;
baffle_rim_mm = 12;
shell_wall_mm = 4;
rear_depth_mm = 20;
back_plate_mm = 6;
joint_screws = 6;
joint_screw_circle_mm = 82;
joint_oring_id_mm = 68;
joint_oring_cs_mm = 1.5;
shell_flange_mm = 5;
cable_hole_diameter_mm = 2.5;
plug_diameter_mm = 14;
plug_groove_diameter_mm = 11.8;
plug_groove_width_mm = 2;
plug_clearance_mm = 0.1;
drill_allowance_mm = 0.4;
rear_hole_diameter_mm = 3;
rear_mesh_hole_diameter_mm = 8;
front_hole_diameter_mm = 8;
front_ports = 2;
