//! The open reference cup (spec Section 17, docs/reference-cup.md): the
//! dimensions, the CAD include and the netlist agree; every configuration of
//! the protocol solves within its operating limits; the frozen blind
//! predictions match their manifest, whose own SHA-256 is pinned here; the
//! drift of the current engine from them is reported without failing; and
//! the validation pipeline, run on synthetic sessions from the virtual rig,
//! passes a true cup within its tolerances, fails a cup with a model-form
//! error, and reports missing files and sidecars that break the protocol.
//!
//! The end-to-end tests run the model at level 0 (lumped cavities) for both
//! the true cup and the fit, so that they stay fast in debug builds; the
//! pipeline is the same at level 1 (`full_session_at_level_1`, ignored:
//! run it with `cargo test --release -p acoustilab --test reference_cup --
//! --ignored --nocapture`).

use acoustilab::expr::PValue;
use acoustilab::params::{Overrides, Parametric};
use acoustilab::validation::predict::{self, Frozen};
use acoustilab::validation::session::{self, Severity, ValidateOptions};
use acoustilab::validation::simulate::{self, SimulateOptions};
use acoustilab::validation::{Files, Protocol};
use acoustilab::Circuit;
use serde_json::{json, Value};
use std::path::{Path, PathBuf};

/// SHA-256 of every frozen manifest. A frozen prediction is never changed:
/// a new one goes into a new version directory, and its manifest's hash is
/// added here in the same commit, where a reviewer sees it.
const FROZEN: &[(&str, &str)] = &[(
    "v1",
    "29dd01983da36b58737833b4eb1bc0b97b6645354df5233120fa01454dd0014e",
)];

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn read(rel: &str) -> String {
    std::fs::read_to_string(root().join(rel)).unwrap_or_else(|e| panic!("{rel}: {e}"))
}

fn read_dir(dir: &Path) -> Files {
    let mut files = Files::new();
    for e in std::fs::read_dir(dir).unwrap_or_else(|e| panic!("{}: {e}", dir.display())) {
        let e = e.unwrap();
        if e.path().is_file() {
            files.insert(
                e.file_name().into_string().unwrap(),
                std::fs::read(e.path()).unwrap(),
            );
        }
    }
    files
}

fn predictions_dir() -> PathBuf {
    root().join("validation/reference_cup/predictions")
}

fn frozen_v1() -> Frozen {
    Frozen::load(&read_dir(&predictions_dir().join("v1"))).expect("load v1")
}

// ----- Dimensions, CAD and netlist ------------------------------------------

/// The include tools/refcup/dims_to_scad.py writes, reproduced.
fn scad_include(dims: &Value) -> String {
    let mut s = String::from(
        "// Generated by tools/refcup/dims_to_scad.py from\n\
         // validation/reference_cup/dimensions.json. Do not edit: edit the JSON\n\
         // and run the script (cargo test checks that this file is current).\n",
    );
    s += &format!("// Licence: {}\n\n", dims["licence"].as_str().unwrap());
    for (name, d) in dims["dimensions"].as_object().unwrap() {
        let x = d["value"].as_f64().unwrap();
        let text = if x.fract() == 0.0 {
            format!("{}", x as i64)
        } else {
            format!("{x}")
        };
        s += &format!("{name} = {text};\n");
    }
    s
}

#[test]
fn dimensions_scad_and_netlist_agree() {
    let dims: Value =
        serde_json::from_str(&read("validation/reference_cup/dimensions.json")).unwrap();
    assert_eq!(
        read("validation/reference_cup/geometry/dimensions.scad"),
        scad_include(&dims),
        "geometry/dimensions.scad is stale: run tools/refcup/dims_to_scad.py"
    );
    let net: Value = serde_json::from_str(&read("examples/reference_cup.json")).unwrap();
    let params = net["parameters"].as_object().unwrap();
    let entries = dims["dimensions"].as_object().unwrap();
    let mut modelled = 0;
    for (name, d) in entries {
        let p = params.get(name);
        if d["model"].as_bool().unwrap() {
            modelled += 1;
            let p = p.unwrap_or_else(|| {
                panic!("'{name}' is a model dimension but not a netlist parameter")
            });
            assert_eq!(
                p["value"], d["value"],
                "'{name}': netlist and dimensions differ"
            );
            assert_eq!(
                p.get("tolerance"),
                d.get("tolerance"),
                "'{name}': the netlist's tolerance must be the dimension's"
            );
        } else {
            assert!(
                p.is_none(),
                "'{name}' is CAD-only but also a netlist parameter"
            );
        }
    }
    for (name, p) in params {
        let group = p.get("group").and_then(Value::as_str).unwrap_or("");
        if group == "Cup geometry" || group == "Driver geometry" {
            assert!(
                entries.get(name).is_some_and(|d| d["model"] == json!(true)),
                "netlist geometry parameter '{name}' is not a model dimension in dimensions.json"
            );
        }
    }
    assert!(modelled >= 15, "{modelled} model dimensions");
    // The volumes the netlist derives, against the CAD's closed forms.
    let p = Parametric::parse(&read("examples/reference_cup.json")).unwrap();
    let v: std::collections::BTreeMap<String, f64> = p
        .values(&Overrides::new())
        .unwrap()
        .into_iter()
        .filter_map(|(k, v)| v.as_num().map(|x| (k, x)))
        .collect();
    let dim = |k: &str| entries[k]["value"].as_f64().unwrap();
    let area = |d: f64| std::f64::consts::PI * d * d / 4.0;
    let rear = area(dim("cup_inner_diameter_mm")) * dim("rear_depth_mm")
        - (area(dim("retainer_outer_diameter_mm")) - area(dim("retainer_inner_diameter_mm")))
            * dim("retainer_thickness_mm")
        - area(dim("driver_rear_boss_diameter_mm"))
            * (dim("driver_overall_depth_mm") - dim("driver_body_depth_mm"));
    assert!((v["rear_volume_cm3"] - rear / 1000.0).abs() < 1e-12);
    let front = area(dim("cup_inner_diameter_mm"))
        * (dim("pad_ring_height_mm") + dim("gasket_compressed_mm"))
        + area(dim("lip_inner_diameter_mm")) * (dim("lip_thickness_mm") + dim("driver_gasket_mm"))
        + v["driver_Sd_cm2"] * 100.0 * dim("diaphragm_setback_mm");
    assert!((v["front_volume_cm3"] - front / 1000.0).abs() < 1e-12);
}

#[test]
fn the_written_protocol_names_every_measurement() {
    let protocol = Protocol::parse(&read("validation/reference_cup/protocol.json")).unwrap();
    let md = read("validation/reference_cup/protocol.md");
    for (c, m) in protocol.measurements() {
        assert!(
            md.contains(&format!("`{}`", m.id)),
            "protocol.md does not name '{}'",
            m.id
        );
        assert!(
            md.contains(&format!("`{}", c.id)),
            "protocol.md does not name '{}'",
            c.id
        );
    }
}

#[test]
fn every_configuration_solves_within_its_operating_limits() {
    let text = read("validation/reference_cup/protocol.json");
    let protocol = Protocol::parse(&text).unwrap();
    // A coarse grid: this checks the netlist, not the curves.
    let freqs: Vec<f64> = (0..12).map(|k| 20.0 * 2f64.powi(k)).collect();
    let p = acoustilab::validation::netlist_on_grid(&read("examples/reference_cup.json"), &freqs)
        .unwrap();
    protocol.check_against(&p).unwrap();
    for c in &protocol.configurations {
        let circuit = Circuit::from_parametric(&p, &protocol.overrides_for(c)).unwrap();
        let r = circuit.solve().unwrap();
        let limits: Vec<String> = r
            .warnings
            .iter()
            .filter(|w| w.limit.is_some())
            .map(|w| w.message.clone())
            .collect();
        assert!(limits.is_empty(), "{}: {limits:?}", c.id);
    }
}

// ----- Frozen predictions ----------------------------------------------------

#[test]
fn frozen_predictions_match_their_manifest() {
    let mut versions = Vec::new();
    for e in std::fs::read_dir(predictions_dir()).unwrap() {
        let e = e.unwrap();
        if e.path().is_dir() {
            versions.push(e.file_name().into_string().unwrap());
        }
    }
    versions.sort();
    assert!(versions.contains(&"v1".to_string()), "{versions:?}");
    for v in &versions {
        let pinned = FROZEN
            .iter()
            .find(|(name, _)| name == v)
            .unwrap_or_else(|| panic!("prediction version '{v}' is not pinned in FROZEN"))
            .1;
        let r = predict::verify(&read_dir(&predictions_dir().join(v)));
        assert!(r.ok, "{v}: {:#?}", r.problems);
        assert_eq!(
            r.manifest_sha256.as_deref(),
            Some(pinned),
            "{v}: the manifest changed; frozen predictions are never edited"
        );
        assert!(r.files_checked > 40, "{v}: {} files", r.files_checked);
    }
}

#[test]
fn verification_refuses_any_change() {
    let dir = predictions_dir().join("v1");
    let files = read_dir(&dir);
    let mut changed = files.clone();
    let csv = changed.get_mut("iec_ref_p.csv").unwrap();
    let last = csv.len() - 2;
    csv[last] = if csv[last] == b'1' { b'2' } else { b'1' };
    let r = predict::verify(&changed);
    assert!(
        !r.ok && r.problems.iter().any(|p| p.contains("iec_ref_p.csv")),
        "{:?}",
        r.problems
    );
    assert!(Frozen::load(&changed).is_err());
    let mut extra = files.clone();
    extra.insert("iec_ref_p_v2.csv".into(), b"1,2\n".to_vec());
    assert!(!predict::verify(&extra).ok);
    let mut missing = files;
    missing.remove("t43_ref_z.envelope.csv");
    assert!(!predict::verify(&missing).ok);
}

#[test]
fn frozen_predictions_are_complete_and_consistent() {
    let f = frozen_v1();
    let m = &f.manifest;
    assert_eq!(m["version"], "v1");
    assert_eq!(
        m["git"]["dirty"],
        json!(false),
        "v1 must come from a clean tree"
    );
    assert!(m["git"]["commit"].as_str().is_some_and(|c| c.len() == 40));
    assert_eq!(
        m["netlist"]["sha256"].as_str().unwrap(),
        acoustilab::validation::sha256_hex(f.netlist_text.as_bytes())
    );
    for c in m["configurations"].as_array().unwrap() {
        let mc = &c["monte_carlo"];
        assert_eq!(mc["runs"], json!(f.protocol.mc_runs), "{}", c["id"]);
        assert_eq!(mc["failed"], json!(0), "{}: {}", c["id"], mc["failures"]);
    }
    for (conf, meas) in f.protocol.measurements() {
        let nominal = &f.nominal[&meas.id];
        let env = &f.envelopes[&meas.id];
        assert_eq!(nominal.freqs_hz, env.freqs, "{}", meas.id);
        assert!(env.freqs[0] >= conf.band.0 && *env.freqs.last().unwrap() <= conf.band.1);
        let level = match env.quantity {
            acoustilab::io::Quantity::Pressure => nominal.level_db(),
            _ => nominal.magnitude.clone(),
        };
        for (i, l) in level.iter().enumerate() {
            assert_eq!(*l, env.nominal[i], "{} at {} Hz", meas.id, env.freqs[i]);
            assert!(
                env.min[i] <= env.p5[i] && env.p5[i] <= env.median[i],
                "{} at {}",
                meas.id,
                env.freqs[i]
            );
            assert!(
                env.median[i] <= env.p95[i] && env.p95[i] <= env.max[i],
                "{} at {}",
                meas.id,
                env.freqs[i]
            );
            assert_eq!(env.n[i], f.protocol.mc_runs);
        }
        // The frozen sidecar states the protocol's conditions.
        let sc = &nominal.sidecar;
        assert_eq!(
            sc.reference_point.as_deref(),
            Some(meas.reference_point.as_str())
        );
        assert_eq!(sc.compensation.as_deref(), Some("none"));
        assert!(sc.drive.is_some());
        if let Some(fx) = conf.sidecar.get("fixture") {
            assert_eq!(sc.fixture.as_deref(), fx.as_str());
        }
    }
}

/// Non-failing: how far the current engine (and the current netlist) has
/// moved from the frozen predictions. A blind prediction is never updated;
/// this only makes model changes visible.
#[test]
fn drift_from_the_frozen_predictions() {
    let f = frozen_v1();
    let d = predict::drift(&f, Some(&read("examples/reference_cup.json"))).expect("drift runs");
    println!("{}", d.summary());
    assert_eq!(d.engine.len(), f.nominal.len());
}

// ----- The pipeline on synthetic sessions ------------------------------------

/// The frozen set with only some configurations kept (to bound the run
/// time of a test).
fn restricted(ids: &[&str]) -> Frozen {
    let mut f = frozen_v1();
    f.protocol
        .configurations
        .retain(|c| ids.contains(&c.id.as_str()));
    assert_eq!(f.protocol.configurations.len(), ids.len());
    f
}

fn lumped() -> Overrides {
    Overrides::from([("fidelity".to_string(), PValue::Num(0.0))])
}

fn files_of(s: std::collections::BTreeMap<String, String>) -> Files {
    s.into_iter().map(|(k, v)| (k, v.into_bytes())).collect()
}

fn sim(f: &Frozen, truth: &[(&str, f64)], netlist: Option<String>, seed: u64) -> Files {
    let mut o = SimulateOptions {
        seed,
        netlist_text: netlist,
        points_per_octave: 12.0,
        ..SimulateOptions::default()
    };
    o.truth = lumped();
    for (k, v) in truth {
        o.truth.insert(k.to_string(), PValue::Num(*v));
    }
    files_of(simulate::simulate(f, &o).expect("simulate"))
}

fn validate(f: &Frozen, files: &Files, anchor: bool) -> session::Report {
    let opts = ValidateOptions {
        extra_overrides: lumped(),
        anchor_driver: anchor,
        fit_points_per_octave: Some(12.0),
        max_evaluations: 100,
    };
    session::validate(f, files, &opts, &mut |_| {}).expect("validate")
}

fn spec_pass(r: &session::Report, id: &str) -> bool {
    let m = r.measurement(id).unwrap();
    assert!(m.errors.is_empty(), "{id}: {:?}", m.errors);
    m.acceptance
        .iter()
        .find(|a| a.variant == "spec")
        .unwrap_or_else(|| panic!("{id}: no acceptance run"))
        .pass
}

/// The frozen netlist with the driver's internal rear path the model
/// leaves out: a volume behind the diaphragm and an acoustic mass (the
/// rear holes) in series with the rear chamber.
fn with_internal_rear_path(netlist: &str, mass_kg_per_m4: f64, volume_cm3: f64) -> String {
    let mut d: Value = serde_json::from_str(netlist).unwrap();
    let els = d["elements"].as_array_mut().unwrap();
    let drv = els.iter_mut().find(|e| e["id"] == "drv").unwrap();
    drv["nodes"][3] = json!("=if(in_cup, 'a_int', 'ambient')");
    els.push(json!({"id": "int_vol", "type": "cavity", "node": "a_int",
                    "volume_cm3": volume_cm3, "enabled": "=in_cup"}));
    els.push(
        json!({"id": "int_vent", "type": "acoustic_impedance", "nodes": ["a_int", "a_rear"],
                    "M_kg_per_m4": mass_kg_per_m4, "R_Pa_s_per_m3": 3e4, "enabled": "=in_cup"}),
    );
    d["nodes"]
        .as_array_mut()
        .unwrap()
        .push(json!({"id": "a_int", "domain": "acoustic", "enabled": "=in_cup"}));
    d.to_string()
}

#[test]
fn a_true_cup_within_its_tolerances_passes() {
    let f = restricted(&["driver_free", "iec_ref", "t43_ref"]);
    // Every perturbation is inside the frozen tolerances, and the leak and
    // front volume (fitted) are far from their nominal values.
    let truth = [
        ("driver_Bl_factor", 1.04),
        ("driver_compliance_factor", 1.2),
        ("driver_Rms_factor", 0.9),
        ("driver_Mms_g", 0.31),
        ("mesh_rayl", 240.0),
        ("front_volume_factor", 1.06),
    ];
    let files = sim(&f, &truth, None, 7);
    let t0 = std::time::Instant::now();
    let r = validate(&f, &files, true);
    println!(
        "{}\nvalidated in {:.1} s",
        r.summary(),
        t0.elapsed().as_secs_f64()
    );
    assert!(r.verdict.complete, "{:?}", r.verdict);
    assert!(r.verdict.synthetic);
    assert_eq!(r.verdict.sidecar_errors, 0);
    for id in ["iec_ref_p", "t43_ref_p"] {
        assert!(spec_pass(&r, id), "{}", r.summary());
        let a = r.measurement(id).unwrap();
        let fitted = &a.acceptance[0].fitted;
        let volume = fitted
            .iter()
            .find(|p| p.name == "front_volume_factor")
            .unwrap();
        assert!((volume.value - 1.06).abs() < 0.03, "{id}: {volume:?}");
    }
    // The driver anchor recovers the true driver from its free-air
    // impedance, and the anchored runs pass too.
    let anchor = r.driver_anchor.as_ref().expect("anchor");
    let get = |n: &str| anchor.fitted.iter().find(|p| p.name == n).unwrap().value;
    assert!(
        (get("driver_Bl_factor") / 1.04 - 1.0).abs() < 0.02,
        "{anchor:?}"
    );
    for id in ["iec_ref_p", "t43_ref_p"] {
        let m = r.measurement(id).unwrap();
        assert!(m
            .acceptance
            .iter()
            .any(|a| a.variant == "driver_anchored" && a.pass));
    }
    // The blind comparison is reported apart from the acceptance: here the
    // true cup differs from the frozen nominal, so its residuals are not
    // zero, and nothing in it is a pass or fail.
    let b = r.measurement("iec_ref_p").unwrap().blind.as_ref().unwrap();
    assert!(b
        .bands
        .iter()
        .all(|x| x.pass.is_none() && x.bound_db.is_none()));
    // The verdict covers the reference states of the (restricted)
    // protocol: here the IEC and Type 4.3 ones.
    assert_eq!(r.verdict.reference_pass, Some(true));
}

#[test]
fn a_model_form_error_fails_and_a_small_one_passes() {
    let f = restricted(&["iec_ref"]);
    // The driver's rear holes as a 350 kg/m^4 mass (two 2.7 mm holes
    // through 1 mm, with their end corrections) resonate with the rear
    // chamber near 400 Hz: the fit of leak and front volume cannot absorb
    // that, and the bounds catch it.
    let large = with_internal_rear_path(&f.netlist_text, 350.0, 2.0);
    let r = validate(&f, &sim(&f, &[], Some(large), 3), false);
    assert!(!spec_pass(&r, "iec_ref_p"), "{}", r.summary());
    let a = &r.measurement("iec_ref_p").unwrap().acceptance[0];
    println!(
        "large: {:?}",
        a.bands
            .iter()
            .map(|b| (b.max_abs_db, b.at_hz))
            .collect::<Vec<_>>()
    );
    assert!(
        a.bands[0].pass == Some(false) && a.bands[0].max_abs_db > 4.0,
        "{:?}",
        a.bands
    );
    // A tenth of it stays within the bounds.
    let small = with_internal_rear_path(&f.netlist_text, 3.0, 0.1);
    let r = validate(&f, &sim(&f, &[], Some(small), 3), false);
    let a = &r.measurement("iec_ref_p").unwrap().acceptance[0];
    println!(
        "small: {:?}",
        a.bands
            .iter()
            .map(|b| (b.max_abs_db, b.at_hz))
            .collect::<Vec<_>>()
    );
    assert!(spec_pass(&r, "iec_ref_p"), "{}", r.summary());
}

#[test]
fn missing_files_and_protocol_violations_are_reported() {
    let f = restricted(&["cup_free_sealed", "iec_ref", "t43_ref"]);
    let mut files = sim(&f, &[], None, 11);
    // t43_ref_p never measured, one seating of iec_ref_z lost.
    files.retain(|k, _| !k.starts_with("t43_ref_p_") && !k.starts_with("iec_ref_z_s5."));
    // A wrong fixture, a smoothed export, a different drive and a missing
    // sidecar.
    let edit = |files: &mut Files, name: &str, f: &dyn Fn(&mut Value)| {
        let mut v: Value = serde_json::from_slice(&files[name]).unwrap();
        f(&mut v);
        files.insert(name.into(), v.to_string().into_bytes());
    };
    edit(&mut files, "iec_ref_p_s1.frd.sidecar.json", &|v| {
        v["fixture"] = json!("head and torso simulator")
    });
    edit(&mut files, "iec_ref_p_s2.frd.sidecar.json", &|v| {
        v["smoothing"] = json!("1/6")
    });
    edit(&mut files, "iec_ref_p_s3.frd.sidecar.json", &|v| {
        v["drive"] = json!({"voltage_V": 1})
    });
    files.remove("cup_free_sealed_z_s2.zma.sidecar.json");
    files.insert("notes.txt".into(), b"bench notes".to_vec());
    let r = validate(&f, &files, false);
    assert!(!r.verdict.complete);
    assert_eq!(r.verdict.missing, vec!["t43_ref_p".to_string()]);
    assert!(
        r.verdict.incomplete.contains(&"iec_ref_z".to_string()),
        "{:?}",
        r.verdict
    );
    assert!(
        r.verdict.incomplete.contains(&"iec_ref_p".to_string()),
        "{:?}",
        r.verdict
    );
    assert_eq!(r.verdict.reference_pass, None);
    let p = r.measurement("iec_ref_p").unwrap();
    assert_eq!(p.seatings, 2, "three files break the protocol");
    let errs = |file: &str, field: &str| {
        p.issues
            .iter()
            .any(|i| i.file == file && i.field == field && i.severity == Severity::Error)
    };
    assert!(errs("iec_ref_p_s1.frd", "fixture"));
    assert!(errs("iec_ref_p_s2.frd", "smoothing"));
    assert!(errs("iec_ref_p_s3.frd", "drive"));
    let z = r.measurement("cup_free_sealed_z").unwrap();
    assert!(z
        .issues
        .iter()
        .any(|i| i.field == "sidecar" && i.severity == Severity::Error));
    assert!(r.unrecognised_files.contains(&"notes.txt".to_string()));
    let text = r.summary();
    assert!(
        text.contains("Incomplete session") && text.contains("t43_ref_p"),
        "{text}"
    );
    // The report says the acceptance was not evaluated rather than passing.
    assert!(text.contains("not evaluated"), "{text}");
}

#[test]
fn session_templates_name_every_file() {
    let f = frozen_v1();
    let t = session::session_templates(&f);
    let checklist = &t["SESSION.txt"];
    for (c, m) in f.protocol.measurements() {
        assert!(checklist.contains(&m.id), "{}", m.id);
        for k in 1..=c.seatings {
            let name = format!("{}_s{k}.sidecar.json", m.id);
            let sc = acoustilab::io::Sidecar::parse(&t[&name]).unwrap();
            assert_eq!(
                sc.reference_point.as_deref(),
                Some(m.reference_point.as_str())
            );
            assert!(sc.source_impedance_ohm.is_none() && sc.temperature_c.is_none());
        }
    }
}

/// The whole protocol at level 1 (about 3 minutes in a release build).
#[test]
#[ignore]
fn full_session_at_level_1() {
    let f = frozen_v1();
    let files = files_of(
        simulate::simulate(
            &f,
            &SimulateOptions {
                seed: 5,
                ..SimulateOptions::default()
            },
        )
        .unwrap(),
    );
    let r = session::validate(&f, &files, &ValidateOptions::default(), &mut |l| {
        eprintln!("{l}")
    })
    .unwrap();
    println!("{}", r.summary());
    assert!(r.verdict.complete);
    assert_eq!(r.verdict.reference_pass, Some(true));
}
